spring:
    jpa:
        database: POSTGRESQL
        show-sql: true
        hibernate:
            ddl-auto: update
    datasource:
        platform: postgres
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://ec2-52-30-133-191.eu-west-1.compute.amazonaws.com:5432/dciloq6v55lj2
        username: qpgtcubmheksgr
        password: f6f969291670412f54420365b9bbe37311eb3ba461643c7a9277914aa82c86a2

server:
    error:
        include-message: always